project_id = "cylsbcjqemluouxblywl"

[functions.semantic-search]
verify_jwt = false

[functions.malware-scan]
verify_jwt = true

[functions.session-manager]
verify_jwt = true

[functions.anomaly-detector]
verify_jwt = true
