project_id = "cylsbcjqemluouxblywl"

[functions.semantic-search]
verify_jwt = false

[functions.malware-scan]
verify_jwt = true

[functions.session-manager]
verify_jwt = true

[functions.anomaly-detector]
verify_jwt = true

[functions.ai-recommendations]
verify_jwt = false

[functions.advanced-search]
verify_jwt = false

[functions.backup-manager]
verify_jwt = true

[functions.security-report-generator]
verify_jwt = true

[functions.notification-manager]
verify_jwt = true
